### ISSUE TITLE
Redefine Constants

### ISSUE THREAD

**Issue by beberlei** [php-test-helpers/php-test-helpers#4]
Constants are quite a nightmare for any testing scenario as well. Would it be possible to port `runkit_redefine_constant()` to this extension?

**Comment by johannes** [comment]
This had been one of my first ever patches for PHP's C code:
http://news.php.net/php.pecl.dev/1314

The concept should still work, coding style has to be changed from APD's to PHP CS and it should use zend_parse_parameters() rather than zend_get_parameters_ex ... all the changes should be straight-forward.

**Comment by johannes** [comment]
Ah there's one flaw with this patch: PHP allows case-insensitive constants and a possible flaw might be in the handling of internal constants.

**Comment by johannes** [comment]
hm, that code is based on PHP 4, so doesn't support class constants, maybe the runkitcode should be ported over instead ... didn't look at that,yet.

**Comment by noginn** [comment]
+1

**Comment by sebastianbergmann** [comment]
This extension is [superseded](https://github.com/php-test-helpers/php-test-helpers/issues/29#issuecomment-44049111) by [uopz](https://github.com/krakjoe/uopz) and is no longer maintained.
