### ISSUE TITLE
set_new_overload() has no effect when Xdebug is loaded

### ISSUE THREAD

**Issue by sebastianbergmann** [php-test-helpers/php-test-helpers#5]

**Comment by johannes** [comment]
Fixed in 3820cd04ed8597e1ebe3474fc1c16734390e540d

For working with xdebug this module can additionally(!) be loaded as zend_extension. When it is loaded as PHP module AND Zend extension it will do all work. If it is loaded as php module only it will work as before. If it is loaded as Zend extension only it will do nothing (but waste a few CPU cycles)

This needs some testing (especially if xdebug is overriding ZEND_NEW and the rename fails due to an invalid classname)

**Comment by johannes** [comment]
Commit c261450f92253d59a9a54f443516efa9b120a67b changes this to be exclusively either a PHP module or Zend extension. Looks and feels cleaner.
